annotator/annotator/apps/sequences/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('apps.sequences.views',
    (r'^$', 'index'),
    (r'^songs/$', 'song_index'),
    (r'^songs/(?P<id>\d+)/$', 'edit_song'),
    (r'^songs/(?P<id>\d+)/delete/$', 'delete_song'),
    (r'^stats_index/$', 'index_with_stats'),
    (r'^notes/$', 'notes_summary'),
    (r'^category_use/$', 'category_use'),
    (r'^omissions/table/$', 'omissions_summary', {'table':True}),
    (r'^omissions/$', 'omissions_summary'),
    (r'^view_all/$', 'view_sequences'),
    (r'^(?P<id>\d+)/delete/$', 'delete_sequence'),
    (r'^(?P<id>\d+)/$', 'edit_sequence'),
    (r'^(?P<id>\d+)/annotate/$', 'annotate_sequence'),
    url(r'^(\d+)/start_reannotate/$', 'reannotate_sequence', { 'new' : True },
            name="start-reannotate"),
    url(r'^(\d+)/reannotate/$', 'reannotate_sequence', { 'new' : False },
            name="reannotate"),
    (r'^add/$', 'add_sequence'),
    (r'^reannotate/$', 'random_reannotate'),
    (r'^reannotated/$', 'reannotated'),
    
    (r'^skipped/$', 'skipped_sequences'),
    (r'^skipped/(?P<id>\d+)/delete/$', 'delete_skipped_sequence'),
    (r'^skipped/(?P<id>\d+)/$', 'edit_skipped_sequence'),
    (r'^skipped/add/$', 'add_skipped_sequence'),
)

annotator/annotator/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Only one app. Put the sequence index at the root as well.
    (r'^$', 'apps.sequences.views.index'),
    (r'^sequences/', include('apps.sequences.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    # Serve static media in the dev environment
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
)

annotator/annotator/apps/sequences/models.py
from django.db import models
import simplejson as json

from apps.sequences.utils import get_chord_list_from_sequence

from jazzparser.utils.chords import int_to_chord_numeral
from jazzparser.utils.base import ExecutionTimer

class ChordType(models.Model):
    """ These should all be set up in a fixture. M7, m7, etc. """
    symbol = models.CharField(max_length=10, blank=True, null=True)
    order = models.IntegerField()
    
    def __unicode__(self):
        return unicode(self.symbol)

class Source(models.Model):
    """ Where a chord sequence comes from. """
    name = models.CharField(max_length=30)
    
    def __unicode__(self):
        return unicode(self.name)
    
class Chord(models.Model):
    """ An individual chord in a sequence. """
    root = models.IntegerField()
    type = models.ForeignKey(ChordType)
    additions = models.CharField(max_length=15, blank=True, null=True)
    bass = models.IntegerField(blank=True, null=True)
    next = models.ForeignKey('Chord', blank=True, null=True)
    duration = models.IntegerField()
    category = models.CharField(max_length=20, blank=True, null=True)
    sequence = models.ForeignKey('ChordSequence', blank=True, null=True)
    
    def to_list(self):
        if self.next is None:
            tail = []
        else:
            tail = self.next.to_list()
        tail.append({
            'id': self.id,
            'root': self.root,
            'type': self.type.id,
            'duration': self.duration,
            'category': self.category,
            'additions': self.additions,
            'bass': self.bass,
            'coord_unresolved' : self.treeinfo.coord_unresolved,
            'coord_resolved' : self.treeinfo.coord_resolved,
        })
        return tail
        
    def __unicode__(self):
        return unicode('%s%s' % (int_to_chord_numeral(self.root), self.type))
        
    def __str__(self):
        return str(unicode(self))
        
    def _get_jp_input(self):
        """ A string format suitable for input to the Jazz Parser. """
        return "%s%s" % (int_to_chord_numeral(self.root), self.type.symbol)
    jazz_parser_input = property(_get_jp_input)
    
    def get_chord_mirror(self, sequence=None):
        """
        Produces a mirror of just this chord (no successors).
        The sequence argument should be a mirror of the sequence (we 
        don't want to create a new mirror for every chord).
        """
        from jazzparser.data.db_mirrors import Chord as ChordMirror
        ti = self.treeinfo.get_mirror()
        return ChordMirror(
            root=self.root, type=self.type.symbol, additions=self.additions,
            bass=self.bass, next=None, duration=self.duration, 
            category=self.category, sequence=sequence, treeinfo=ti)
    
    def get_mirror(self, sequence=None):
        """
        Produces a mirror of this chord and all its successors.
        The sequence argument should be a mirror of the sequence (we 
        don't want to create a new mirror for every chord).
        """
        chord = self.get_chord_mirror(sequence)
        if self.next is not None:
            chord.next = self.next.get_mirror(sequence)
        return chord
        
    def _get_treeinfo(self):
        try:
            return self._treeinfo
        except TreeInfo.DoesNotExist:
            new_info = TreeInfo()
            new_info.chord = self
            return new_info
    treeinfo = property(_get_treeinfo)
    
    @property
    def index(self):
        """
        The index of the chord within its sequence.
        """
        if not hasattr(self, "__index"):
            self.__index = list(self.sequence.iterator()).index(self)
        return self.__index
    
class Song(models.Model):
    """
    Represents a single song. Note that a song may have more than 
    one chord sequence associated with it.
    
    """
    name = models.CharField(max_length=50)
    key = models.CharField(max_length=20, blank=True, null=True)
    notes = models.TextField(blank=True, null=True, help_text="General notes about the song")
    
    def __unicode__(self):
        return self.name
        
    def _get_string_name(self):
        return self.name.encode('ascii', 'replace')
    string_name = property(_get_string_name)

class ChordSequence(models.Model):
    """
    A chord sequence for a song.
    
    """
    song = models.ForeignKey(Song, null=True)
    description = models.CharField(max_length=256, blank=True, null=True, help_text="Descriptive text specific to this chord sequence, distinguishing it from others for the same song.")
    bar_length = models.IntegerField()
    first_chord = models.ForeignKey(Chord, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)
    analysis_omitted = models.BooleanField(help_text="The analysis has been left out entirely, because the sequence doesn't suit this kind of analysis or I have no idea how to do it.")
    omissions = models.TextField(blank=True, null=True, help_text="A simple list of the gaps in the analyis")
    source = models.ForeignKey(Source, null=True, help_text="Where the sequence came from")
    alternative = models.BooleanField(help_text="This is an alternative annotation of the chord sequence. It will not be included in the default exported data set, unless requested for consistency testing")
    
    def to_json(self):
        if self.first_chord is not None:
            chord_data = list(reversed(self.first_chord.to_list()))
        else:
            chord_data = {}
        return json.dumps(chord_data)
        
    def __unicode__(self):
        return unicode(self.name)
        
    @property
    def string_name(self):
        return self.song.string_name
        
    @property
    def sequence_distinguisher(self):
        """
        A string that can be used to distinguish this sequence from others
        for the same song, e.g. in interface lists.
        
        """
        if self.description:
            return str(self.description.encode('ascii','replace'))
        else:
            return "%s (%d)" % (self.string_name, self.id)
    
    def delete(self):
        # First delete all the chords
        chords = list(self.iterator())
        for chord in chords:
            chord.delete()
        super(ChordSequence, self).delete()
        
    def iterator(self):
        chord = self.first_chord
        while chord is not None:
            yield chord
            chord = chord.next
            
    def _get_number_annotated(self):
        total = 0
        annotated = 0
        for chord in self.iterator():
            if chord.category is not None and chord.category != "":
                annotated += 1
            total += 1
        return (annotated, total)
    number_annotated = property(_get_number_annotated)
    
    def _get_percentage_annotated(self):
        annotated, total = self.number_annotated
        return 100.0 * float(annotated) / float(total)
    percentage_annotated = property(_get_percentage_annotated)
    
    def _get_fully_annotated(self):
        """
        True if every chord in the sequence is annotated. This should 
        usually be a bit quicker than checking percentage_annotated.
        """
        for chord in self.iterator():
            if chord.category is None or chord.category == "":
                return False
        return True
    fully_annotated = property(_get_fully_annotated)
    
    def _get_length(self):
        return len(list(self.iterator()))
    length = property(_get_length)
    __len__ = _get_length
    
    def get_mirror(self):
        """
        Produces a non-database mirror of the chord sequence, including 
        all its chords.
        """
        from jazzparser.data.db_mirrors import ChordSequence as ChordSequenceMirror
        sequence = ChordSequenceMirror(
            name=self.name, key=self.key, bar_length=self.bar_length, 
            first_chord=None, notes=self.notes, 
            analysis_omitted=self.analysis_omitted, omissions=self.omissions,
            source=self.source.name, id=self.id)
        # Mirror all the chords too
        if self.first_chord is not None:
            chord = self.first_chord.get_mirror(sequence)
        sequence.first_chord = chord
        return sequence
    mirror = property(get_mirror)
    
    """
    The following properties provide direct access to the fields of 
    the related song and maintain backwards compatibility (for reading 
    only) from when these were stored on the ChordSequence model.
    """
    def _get_name(self):
        return self.song.name
    name = property(_get_name)
    
    def _get_key(self):
        return self.song.key
    key = property(_get_key)
    
class TreeInfo(models.Model):
    """
    Associates information with a chord that is relevant to building 
    syntactic trees. This stores all information that is not implicit
    in the lexical categories (e.g. where coordinations occur).
    
    """
    chord = models.OneToOneField(Chord, related_name="_treeinfo")
    coord_unresolved = models.BooleanField(help_text="Mark this as the "\
        "final chord of the first part of a coordinated cadence")
    coord_resolved = models.BooleanField(help_text="Marks this as the "\
        "final chord before the common resolution of a coordination")
        
    def get_mirror(self):
        from jazzparser.data.db_mirrors import TreeInfo as TreeInfoMirror
        return TreeInfoMirror(
                coord_resolved=self.coord_resolved,
                coord_unresolved=self.coord_unresolved)
    mirror = property(get_mirror)
            
class SkippedSequence(models.Model):
    """ Just a note of a sequence that I've not bothered to input 
    (usually because it's out of domain). """
    name = models.CharField(max_length=20)
    reason = models.TextField(null=True, blank=True, help_text="Reason for not annotating.", default="Out of domain")

class MidiData(models.Model):
    """

annotator/annotator/apps/sequences/forms.py
from django.forms import ModelForm
import django.forms as forms

from apps.sequences.models import ChordSequence, Chord, ChordType, \
                    SkippedSequence, Song
from apps.sequences import category_pairs

_root_choices = {
    0: "I",
    1: "bII",
    2: "II",
    3: "bIII",
    4: "III",
    5: "IV",
    6: "bV",
    7: "V",
    8: "bVI",
    9: "VI",
    10: "bVII",
    11: "VII",
}.items()

class SongForm(ModelForm):
    class Meta:
        model = Song

class ChordSequenceForm(ModelForm):
    song = forms.ModelChoiceField(queryset=Song.objects.all(), required=False)
    
    class Meta:
        model = ChordSequence
        
    def __init__(self, *args, **kwargs):
        super(ChordSequenceForm, self).__init__(*args, **kwargs)
        self.fields['first_chord'].widget = forms.widgets.HiddenInput()

class ChordForm(ModelForm):
    root = forms.ChoiceField(choices=_root_choices)
    type = forms.ModelChoiceField(queryset=ChordType.objects.all().order_by('order'), empty_label=None)
    bass = forms.ChoiceField(choices=[('','')]+_root_choices)
    coord_resolved = forms.BooleanField()
    coord_unresolved = forms.BooleanField()
    
    class Meta:
        model = Chord
        
    def __init__(self, *args, **kwargs):
        readonly = kwargs.pop("readonly", False)
        super(ChordForm, self).__init__(*args, **kwargs)
        self.fields['category'] = forms.ChoiceField(choices=[('','')]+category_pairs, required=False)
        
        # Make the fields read only
        if readonly:
            for field in ['root', 'type', 'bass', 'duration', 'additions']:
                self.fields[field].widget.attrs['readonly'] = True

class ChordAnnotationForm(forms.Form):
    MIN_LAYOUT_WIDTH = 100
    PIXELS_PER_BEAT = 70
    
    category = forms.ChoiceField()
    
    def __init__(self, chord, auto_tag, suggestion_initial=True, *args, **kwargs):
        self.chord = chord
        self.auto_tag = auto_tag
        if not suggestion_initial or auto_tag == chord.category:
            # If the suggestion is the same as the old tag, make 'previous' the default choice - it feels better
            initial = {'category':'previous'}
        else:
            initial = {'category':'auto'}
        super(ChordAnnotationForm, self).__init__(*args, initial=initial, **kwargs)
        self.fields['category'] = forms.ChoiceField(choices=[('auto','Suggested tag'),('previous','Old tag (%s)'%chord.category),('','')]+sorted(category_pairs), required=False)
        
    def save(self, *args, **kwargs):
        tag = self.cleaned_data['category']
        # If they selected previous, don't change the tag
        if tag != 'previous':
            if tag == 'auto':
                # They want the automatically annotated tag
                tag = self.auto_tag
            self.chord.category = tag
            # Save the chord with this category
            self.chord.save()
            
    def _get_layout_width(self):
        """
        The number of pixels to use for the layout of this chord form.
        """
        return max(ChordAnnotationForm.MIN_LAYOUT_WIDTH, self.chord.duration * ChordAnnotationForm.PIXELS_PER_BEAT)
    layout_width = property(_get_layout_width)
    
class SkippedSequenceForm(forms.ModelForm):
    class Meta:
        model = SkippedSequence

annotator/annotator/templates/sequences/category_use.html
{% extends 'base.html' %}

{% block page_title %}Category Use Summary | {% endblock %}

{% block content %}
	<h1>Category Use Summary</h1>
	<div class="box">
		<table class="category_use">
			<tr>
				<th>Category</th> <th>Count</th> <th>Proportion</th>
			</tr>
			{% for row in table_data %}
			<tr>
				<td>{{ row.category }}</td>
				<td class="number">{{ row.count }}</td>
				<td class="number">{{ row.percent }}%</td>
			</tr>
			{% endfor %}
		</table>
		<p>Total chords: {{ total }}</p>
	</div>
{% endblock %}

annotator/annotator/templates/sequences/delete_sequence.html
{% extends 'base.html' %}

{% block page_title %}Delete "{{ sequence.name }}" | {% endblock %}

{% block content %}
	<h1>Delete chord sequence: {{ sequence.name }}</h1>
	<div class="box">
		<form class="standard_form" action="." method="post">
			<p>Are you sure you want to delete the chord sequence "{{ sequence.name }}"?</p>
			<div class="actions">
				<input type="submit" name="delete" value="Yes"/>
				<input type="submit" name="cancel" value="No"/>
			</div>
		</form>
	</div>
{% endblock %}

annotator/annotator/templates/sequences/delete_song.html
{% extends 'base.html' %}

{% block page_title %}Delete "{{ song.name }}" | {% endblock %}

{% block content %}
	<h1>Delete song: {{ song.name }}</h1>
	<div class="box">
		<form class="standard_form" action="." method="post">
			<p>Are you sure you want to delete the song "{{ song.name }}"?
			Any chord sequences for this song will also be deleted.</p>
			<div class="box">
				<p>Chord sequences affected:</p>
				<ul>
					{% for seq in song.chordsequence_set.all %}
						<li>{{ forloop.counter }}. Sequence {{ seq.id }}{% if seq.description %}: {{ seq.description }}{% endif %}</li>
					{% endfor %}
				</ul>
			</div>
			<div class="actions">
				<input type="submit" name="delete" value="Yes"/>
				<input type="submit" name="cancel" value="No"/>
			</div>
		</form>
	</div>
{% endblock %}

annotator/annotator/templates/sequences/edit_sequence.html
{% extends 'base.html' %}

{% block page_title %}{% if sequence.name %}Edit Sequence: {{ sequence.name }}{% else %}Add new sequence{% endif %} | {% endblock %}

{% block extra_head %}
	<script src="{{ MEDIA_URL }}js/sequences.js" type="text/javascript"></script>
	<script type="text/javascript">
		window.addEvent('domready', function() {
			window.chordRoots = {{% for root_pair in chord_roots %}
				{{ root_pair.0 }} : "{{ root_pair.1 }}"{% if not forloop.last %},{% endif %}{% endfor %}
			};
			window.chordTypes = {{% for type_pair in chord_types %}
				{{ type_pair.0 }} : "{{ type_pair.1 }}"{% if not forloop.last %},{% endif %}{% endfor %}
			};
			window.categories = {{% for cat_pair in categories %}
				"{{ cat_pair.0 }}" : "{{ cat_pair.1 }}"{% if not forloop.last %},{% endif %}{% endfor %}
			};
			window.pos_tags = [ {% for tag in pos_tags %}'{{ tag }}'{% if not forloop.last %}, {% endif %}{% endfor %} ];
			// Initialize the chord editor
			window.chordEditor = new ChordEditor('chord_editor', {{ chord_editor_options|safe }});
			var reinitChordEditor = function() {
				var options = new Hash({{ chord_editor_options|safe }});
				options.extend({
						'bar_length': $('id_bar_length').value
					});
				window.chordEditor.recalculateWidth(options);
			}
			$('id_bar_length').addEvent('change', reinitChordEditor());
			$('id_name').focus();
		});
	</script>
{% endblock %}

{% block content %}
	<h1>{% block heading %}{% if sequence.name %}Edit: {{ sequence.name }}{% else %}New sequence{% endif %}{% endblock %}</h1>
	{% if form.errors %}
		{{ form.errors }}
	{% endif %}
	{% if song_form.errors %}
		{{ song_form.errors }}
	{% endif %}
	<div id="editor_form_container" class="{% block container_class %}{% endblock %}">
		<form action="." method="post" class="standard_form" id="editor_form">
			<div class="actions">
				<input type="submit" value="Save" name="save"/>
				<input type="submit" value="Save and exit" name="save_and_exit"/>
				<input type="submit" value="Cancel" name="cancel"/>
				{% if sequence.id %}
				<div class="delete_sequence"><a href="{% url apps.sequences.views.delete_sequence sequence.id %}">Delete</a></div>
				{% endif %}
			</div>
			<div class="box" id="top_form">
				{% block form_box %}
				{{ form.song.errors }}
				<label for="id_song">Song:</label>
				{{ form.song }}
				
				<div class="box">
					<p class="note">
					These will be ignored if you change the song above to 
					anything other than blank (in which case a new song 
					will be created).
					</p>
					{{ song_form.name.errors }}
					<label for="id_song-name">Name:</label>
					{{ song_form.name }}
					
					{{ song_form.key.errors }}
					<label for="id_song-key">Main key:</label>
					{{ song_form.key }}
				</div>
				
				{{ form.bar_length.errors }}
				<label for="id_bar_length">Bar length:</label>
				{{ form.bar_length }}
				
				{{ form.description.errors }}
				<label for="id_description">Sequence description:</label>
				{{ form.description }}
				
				{{ form.source.errors }}
				<label for="id_source">Source:</label>
				{{ form.source }}
				
				{{ form.analysis_omitted.errors }}
				<label for="id_analysis_omitted">Analysis omitted:</label>
				{{ form.analysis_omitted }}
				
				{{ form.alternative.errors }}
				<label for="id_alternative">Alternative analysis:</label>
				{{ form.alternative }}
				{% endblock %}
			</div>
			<div class="box">
				<div id="chord_editor">
					<div id="chord_editor_chords"></div>
					<a href="#" id="edit_as_text_button">Edit as text</a>
				</div>
				<input type="hidden" name="chords" id="chord_editor_data" value='{{ chord_data|safe }}'/>
			</div>
			<div id="text_chord_editor">
				<textarea id="text_chords"></textarea><br/>
				<a id="id_submit_text_chords" href="#">Update</a>
				<a id="id_cancel_text_chords" href="#">Cancel</a>
			</div>
			{% if not hidenotes %}
			<div class="box notes">
				<label for="id_notes">Notes</label>
				{{ form.notes }}
			</div>
			<div class="box omissions">
				<label for="id_omissions">Omissions</label>
				{{ form.omissions }}
			</div>
			{% endif %}
			<div class="actions">
				<input type="submit" value="Save" name="save" accesskey="s"/>
				<input type="submit" value="Save and exit" name="save_and_exit"/>
				<input type="submit" value="Cancel" name="cancel"/>
				{% if sequence.id %}
				<div class="delete_sequence"><a href="{% url apps.sequences.views.delete_sequence sequence.id %}">Delete</a></div>
				{% endif %}
			</div>
		</form>
		<div id="editor_box">
			<form class="standard_form" id="chord_editor_form">
				<div id="editor_pointer"></div>
				<div class="field_container">
					<label id="label_root" for="id_root">Chord</label>
					{{ chord_form.root }}
					{{ chord_form.type }}<br/>
				</div>
				<div class="field_container">
					<label for="id_additions">Additions</label>
					{{ chord_form.additions }}
				</div>
				<div class="field_container">
					<label for="id_bass">Bass</label>
					{{ chord_form.bass }}
				</div>
				<div class="field_container">
					<label for="id_duration" accesskey="d"><strong>D</strong>uration</label>
					{{ chord_form.duration }}
				</div>
				<div class="field_container">
					<label for="id_category" accesskey="c"><strong>C</strong>ategory</label>
					{{ chord_form.category }}
				</div>
				<div class="tree">
					<div class="field_container">
						<label for="id_coord_unresolved">Mid-coord</label>
						{{ chord_form.coord_unresolved }}
					</div>
					<div class="field_container">
						<label for="id_coord_unresolved">End coord</label>
						{{ chord_form.coord_resolved }}
					</div>
				</div>
				<input type="submit" id="save_chord_button" value="Update" accesskey="u"/>
				<div class="close_button"><a href="#" id="editor_box_close">X</a></div>
				<div class="chord_number" id="editor_chord_number"></div>
				<div class="chord_copier" id="editor_chord_copier">
					<label for="id_copy_start" class="copy_start_label">Copy from</label><input type="text" name="copy_start" id="id_copy_start"/>
					<label for="id_copy_end">to</label><input type="text" name="copy_end" id="id_copy_end"/>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

annotator/annotator/templates/sequences/edit_song.html
{% extends 'base.html' %}

{% block content %}
	<h1>Edit Song</h1>
	<div class="box">
		<form class="standard_form" method="POST" action=".">
			{% for field in form %}
				{{ field.errors }}
				{{ field.label_tag }}
				{{ field }}
			{% endfor %}
			<div class="actions">
				<input type="submit" value="Save" name="save" accesskey="s"/>
				<input type="submit" value="Cancel" name="cancel"/>
				{% if song.id %}
				<div class="delete_sequence"><a href="{% url apps.sequences.views.delete_song song.id %}">Delete</a></div>
				{% endif %}
			</div>
		</form>
	</div>
{% endblock %}

annotator/annotator/templates/sequences/notes_summary.html
{% extends 'base.html' %}

{% block page_title %}Notes on Sequences | {% endblock %}

{% block content %}
	<h1>Notes on Chord Sequences</h1>
	<ul class="notes_list box">
		{% for sequence in sequences %}
			<li{% if forloop.last %} class="last"{% endif %}>
				<h2>{{ sequence.name }} <a href="{% url apps.sequences.views.edit_sequence sequence.id %}" class="edit_sequence">[Edit]</a></h2>
				{{ sequence.notes|linebreaks }}
			</li>
		{% endfor %}
	</ul>
{% endblock %}

annotator/annotator/templates/sequences/omissions_summary.html
{% extends 'base.html' %}

{% block page_title %}Omissions in Sequences | {% endblock %}

{% block extra_head %}
	<script src="{{ MEDIA_URL }}js/omissions.js" type="text/javascript"></script>
{% endblock %}

{% block content %}
	<h1>Sequences with Analysis Completely Omitted</h1>
	<ul class="omission_list box">
		{% for sequence in omitted_sequences %}
			<li{% if forloop.last %} class="last"{% endif %}>
				<a href="{% url apps.sequences.views.edit_sequence sequence.id %}">{{ sequence.name }}</a>
			</li>
		{% endfor %}
	</ul>
	<h1>Analysis Omissions in Chord Sequences</h1>
	<ul class="notes_list box">
		{% for sequence in sequences %}
			<li{% if forloop.last %} class="last"{% endif %}>
				<h2>{{ sequence.name }} <a href="{% url apps.sequences.views.edit_sequence sequence.id %}" class="edit_sequence">[Edit]</a></h2>
				{{ sequence.omissions|linebreaks }}
				{% if sequence.notes %}
					<div class="omission_notes_container">
						<a href="#" class="show_notes" id="omission_notes_toggler_{{ sequence.id }}" onclick="showNotesClicked({{ sequence.id }}); return false;">Show notes</a>
						<div class="omission_notes" id="omission_notes_{{ sequence.id }}">{{ sequence.notes|linebreaks }}</div>
					</div>
				{% endif %}
			</li>
		{% endfor %}
	</ul>
{% endblock %}

annotator/annotator/templates/sequences/song_index.html
{% extends 'base.html' %}

{% block extra_head %}
	<script src="{{ MEDIA_URL }}js/tools.js" type="text/javascript"></script>
	<script type="text/javascript">
		window.addEvent('domready', function() {
			{% for letter_group in songs_by_letter %}
				new HideableSection('letter_{{ forloop.counter }}_head', 'letter_{{ forloop.counter }}_section');
			{% endfor %}
		});
	</script>
{% endblock %}

{% block content %}
	<h1>Songs</h1>
	<ol class="sequence_list box">
		{% for letter_group in songs_by_letter %}
			<h2><a name="{{ letter_group.0 }}" href="#" id="letter_{{ forloop.counter }}_head">{{ letter_group.0 }}</a></h2>
			<div class="letter_group_count">({{ letter_group.1|length }})</div>
			<div id="letter_{{ forloop.counter }}_section" class="letter_group_section">
			{% for song in letter_group.1 %}
				<li{% if sequence.analysis_omitted %} class="no_analysis"{% endif %}>
					<a href="{% url apps.sequences.views.edit_song song.id %}">{{ song.name }} {% block sequence_info %}{% endblock %}</a>
					<ul class="song_sequence_list">
						{% for seq in song.chordsequence_set.all %}
						<li><a href="{% url apps.sequences.views.edit_sequence seq.id %}">{{ seq.id }}{% if seq.description %}: {{ seq.description }}{% endif %}{% if seq.alternative %} (alt){% endif %}</a></li>
						{% endfor %}
					</ul>
				</li>
			{% endfor %}
			</div>
		{% endfor %}
		<div class="clear"></div>
	</ol>
{% endblock %}